# Generated by Django 3.1.5 on 2021-06-06 15:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=100)),
                ('cover_image', models.ImageField(blank=True, upload_to='post_cover_image')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(help_text='Post Body')),
                ('publish_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_on', models.DateTimeField()),
                ('views', models.IntegerField(default=0)),
                ('post_state', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED')], default='DRAFT', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_by_user', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='posts_under_this_category', to='posts.Categories')),
                ('tags', models.ManyToManyField(related_name='posts_under_this_tag', to='posts.Tags')),
            ],
            options={
                'ordering': ['-publish_datetime'],
            },
        ),
    ]
